fitur_addfriends/urls.py
from django.conf.urls import url
from .views import index
#url for addfriends
urlpatterns = [
    url(r'^$', index, name='index'),
]

fitur_profil/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

fitur_stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^', index, name='index'),
]

fitur_updStatus/urls.py
from django.conf.urls import url
from .views import index, add_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status/', add_status, name='add_status'),
]

tugas1ppw/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import RedirectView
import fitur_stats.urls as stats
import fitur_addfriends.urls as friends
import fitur_updStatus.urls as upd
import fitur_profil.urls as fitur_profil

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stats/', include(stats,namespace='stats')),
    url(r'^friends/', include(friends, namespace='friends')),
    url(r'^update-status/', include(upd, namespace='update-status')),
    url(r'^profil/', include(fitur_profil,namespace='profil')),
    url(r'^$', RedirectView.as_view(url="update-status/", permanent="false"), name='index'),
]

fitur_addfriends/models.py
from django.db import models

class Friends(models.Model):
    name = models.CharField(max_length=100)
    url = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

fitur_profil/models.py
from django.db import models

# Create your models here.

fitur_stats/models.py
from django.db import models

# Create your models here.

fitur_updStatus/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	content = models.TextField()
	created_date = models.DateTimeField(auto_now_add = True)

fitur_updStatus/forms.py
from django import forms

class Status_Form(forms.Form):
	status_attrs = {
		'type' : 'text',
		'placeholder' : "What's on your mind?"
	}

	status = forms.CharField(label='', required=True, max_length=160, widget=forms.TextInput(attrs=status_attrs))

fitur_addfriends/views.py
from django.shortcuts import render
from .models import Friends



def index(request):
	htmlpage = "friend.html"
	title = "friend"
	response = {"title":title}
	lstFriends = Friends.objects.all()
	response["friends"] = lstFriends

	if request.method == "POST":
		name = request.POST.get("nama","")
		url = request.POST.get("url","")
		friend = Friends(name=name,url=url)
		friend.save()
		response["pesan"] = "data berhasil disimpan"
	
	return render(request,htmlpage,response)	
	

fitur_profil/views.py
from django.shortcuts import render

#Membuat isi dari fitur_profil
name = "Hepzibah Smith"
jenisexpertise = ["Marketing","Collector","Public Speaking"]
bio_dict = [
{'subject' : 'Birthday', 'value' : '10 Oktober 1998'},\
{'subject' : 'Gender', 'value' : 'Male'},\
{'subject' : 'Expertise', 'value' : jenisexpertise},\
{'subject' : 'Description', 'value' : 'Antique expert, Experience as marketer for 10 years'},\
{'subject' : 'Email', 'value' : 'HSmith@gmail.com'},\
]

def index(request):
    response = {'name': name, 'bio_dict': bio_dict, 'title' : 'profil'}
    return render(request, 'fitur_profil/fitur_profil.html', response)

fitur_stats/views.py
from django.shortcuts import render
from fitur_addfriends.models import Friends
from fitur_updStatus.models import Status

# Create your views here.
response = {}
def index(request):
    feeds = Status.objects.all().count()
    html = 'stats/stats.html'
    response['title'] = 'Stats'
    response['friends'] = Friends.objects.all().count()
    response['posts'] = feeds
    if(feeds!=0):
        latestFeed = Status.objects.get(pk=Status.objects.all().count())
        response['latest_post']= latestFeed.content
        response['latest_date']= latestFeed.created_date
    response['username'] = 'Hepzibah Smith'
    return render(request,html,response)

fitur_updStatus/views.py
from django.shortcuts import render
from .models import Status
from .forms import Status_Form
from django.http import HttpResponseRedirect

response = {}

def index(request):
    html = 'update.html'
    status = Status.objects.all()[::-1]
    response['status_form'] = Status_Form
    response['status'] = status
    response['title'] = 'Update Status'

    return render(request, html, response)

def add_status(request):
	form = Status_Form(request.POST or None)
	response['title'] = 'Update Status'
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		if(len(response['status']) > 0 and len(response['status']) <= 160):
			status = Status(content=response['status'])
			status.save()
			return HttpResponseRedirect('/update-status/')
		
	return HttpResponseRedirect('/update-status/')

fitur_addfriends/templates/friend.html
{% extends "base.html" %}

{% block content %}


<h1 class = "main1"> Friends </h1>
{{pesan}}
<table width="150%">
<form method = "POST" action = "{% url 'friends:index' %}">

	{% csrf_token %}
	<tr>
		<td>Nama </td>
		<td><input style = "color:black;" type="text" value="" name="nama" placeholder="Masukkan nama" required="true" size="140"><br></td>
	</tr>
	<tr>
	<td>Url
	</td>
	<td><input style = "color:black;" type="text" value="" name="url" placeholder="Masukkan url" required="true" size="140">
	</td>
	
	</tr>

<input id = "button" style = "color:black;" type="submit" value="add friend" 
 style="position: relative;right: ">
</form>
</table>
<h1>List friends</h1>
<table border="" width="100%">
	{% if friends %}
		{% for friend in friends %}
			<tr>
				<td>
					{{friend.name}}
				</td>
				<td>
					<a href="{{friend.url}}">
					{{friend.url}}
					</a>
				</td>
				<td>
					{{friend.created_date}}
				</td>
			</tr>
		{% endfor %}
	{% else %}
		<h3>tidak ada teman</h3>	
	{% endif %}		

</table>

{% endblock %} 

fitur_profil/templates/fitur_profil/fitur_profil.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h1 style="text-align: center;">Profil</h1>
<center>
<img id="profile" src="{% static "orang/person.jpg" %}"/>
</center>
<h1 style="text-align: center;font-family:verdana;">{{name}}</h1>
<table align="center" >
    {% for bio in bio_dict %}
        <tr>
            <td class="isi" style="font-family:verdana;font-size:110%;">{{bio.subject}}</td>
			{% if bio.subject == 'Expertise'%}
			<td class="value" style="font-family:verdana;font-size:110%;">
			{% for str in bio.value %}
			<span id="expertise" style="font-family:verdana;font-size:110%;">{{str}}</span>
			{% endfor %}
			</td>
			{% else %} <td class="value" style="font-family:verdana;font-size:110%;">{{ bio.value }}</td>
			{% endif %}
        </tr>
    {% endfor %}
</table>
<br>
{% endblock %}

fitur_stats/templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <!-- bootstrap csss -->
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/light_theme.css' %}" id='theme' />  
        <link rel="stylesheet" type="text/css" href="{% static 'css/fitur_profil.css' %}" />  
        <link rel="stylesheet" type="text/css" href="{% static 'css/update.css' %}" />

        <title>{% block title %} {{ title }} {% endblock %}</title>
    </head>
    <body>
        <header>
            {% block header %}
            {% include "partials/header.html" %}
            {% endblock %}
        </header>
        <content>
            <div class="content">
            {% block content %}
            <!--content goes here-->
            {% endblock %}
            </div>
        </content>
        <footer>
            <div class="footer">
            {% block footer %}
            {% include "partials/footer.html" %}
            {% endblock %}
            </div>
        </footer>
        <!-- Jquery n Bootstrap Script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script type="application/javascript">
        $(function() {
            $('a[href*="#"]:not([href="#"])').click(function() {
                if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
                if (target.length) {
                    $('html, body').animate({
                    scrollTop: target.offset().top - 55
                    }, 1000);
                    return false;
                }
                }
            });
            });
        if(localStorage.getItem('theme-selector')==null){
            localStorage.setItem('theme-selector','light')
        }else{
            if(localStorage.getItem('theme-selector')=='dark'){
                document.getElementById('theme').href ="{% static 'css/dark_theme.css' %}";
            }else{
                document.getElementById('theme').href ="{% static 'css/light_theme.css' %}";
            }
        }
        </script>
    </body>
</html>

fitur_stats/templates/partials/footer.html
<p>&copy; Contrived with passion by C14</p>

fitur_stats/templates/partials/header.html
{% load staticfiles %}
{% load static %}

<!-- templates/partials/header.html -->
<nav>
    <div class="container-fluid navbar-fixed-top navbar-color">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar nav-iconbar-color"></span>
                    <span class="icon-bar nav-iconbar-color"></span>
                    <span class="icon-bar nav-iconbar-color"></span>
            </button>
            <a class="navbar-brand" href="#"style="font-size:200%;"><img src="{% static 'img/github-logo.png' %}" class="logo"/>Git Friends</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse" style="font-size:130%;">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/update-status/">Status</a></li>
                <li><a href="/profil/">Profil</a></li>
                <li><a href="/friends/">Friends</a></li>
                <li><a href="/stats/">Dashboard</a></li>
            </ul>
        </div>
    </div>
</nav>

fitur_stats/templates/stats/stats.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}

<div class="stats-outer">
    <div style="margin: 20px">
        <h3>Statistic</h3>
        <div class="stats">
            <img src="{% static 'img/person.jpg' %}" class="profile"/>
            <h1>{{ username }}</h1>
            <div>
                <div class="statistic-left">
                    <h3>Friends : {{ friends }} people</h3>
                </div>
                <div class="statistic-right">
                    <h3>Posts : {{ posts }} posts</h3>
                </div>
            </div>
            <div class="latest-post">
                    <h3>Latest Post</h3>
                    <h4>{{ latest_post }}</h4>
                    <h4>{{ latest_date }}</h4>
            </div>
        </div>    
    </div>
    <div class="theme-section">
        <h3>Change Theme</h3>
        <button id='theme-light-button' class="button-theme">Light Theme</button>
        <button id='theme-dark-button' class="button-theme">Dark Theme</button>
    </div>
</div>

<script>
        document.getElementById('theme-light-button').onclick = function () { 
            document.getElementById('theme').href ="{% static 'css/light_theme.css' %}";
            localStorage.setItem('theme-selector','light')
        };
        document.getElementById('theme-dark-button').onclick = function () { 
            document.getElementById('theme').href ="{% static 'css/dark_theme.css' %}";
            localStorage.setItem('theme-selector','dark')
        };
</script>
{% endblock %}

fitur_updStatus/templates/update.html
{% extends "base.html" %}

{% block content %}

<hr/>
<section>
    <div style="text-align: center;">
        <img src="http://gitfriend.herokuapp.com/static/img/person.jpg" class="photo-in-feed img-circle"></img>
        <br>
        <div class="name-in-feed">Hepzibah Smith</div>
        <form method="POST" action="{% url 'update-status:add_status' %}">
            {% csrf_token %}
            <br>
            <textarea rows="3" cols="40" class="form-control" name="status" placeholder="What's on your mind?"></textarea>
            <br>
            <input type="submit" value="Post" class="btn btn-info">
            <br>
        </form>
    </div>
</section>

<br>
<br>

<section>
    <div class="flex-container">
        <div>
            {% if status %}
                {% for data in status %}
                    <div class="flex-item">
                        <div>
                            <div style="text-align: center;">
                                <img src="http://gitfriend.herokuapp.com/static/img/person.jpg" class="photo-in-feed img-circle">
                                </img>
                            </div>
                            Hepzibah Smith
                            <div style="text-align: center;">
                                {{data.created_date}}
                            </div>
                            <div class="status-in-feed">
                                {{data.content|linebreaksbr}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div>
                <strong>Oops!</strong> Tidak ada data Status.
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}